{{ if .Values.resolvers.endpoint.create }}
---
apiVersion: getambassador.io/v2
kind: KubernetesEndpointResolver
metadata:
  name: {{ .Values.resolvers.endpoint.name }}
  namespace: {{ include "ambassador.namespace" . }}
{{ end }}
{{ if .Values.resolvers.consul.create }}
---
apiVersion: getambassador.io/v2
kind: ConsulResolver
metadata:
  name: {{ .Values.resolvers.consul.name }}
  namespace: {{ include "ambassador.namespace" . }}
spec:
  {{- toYaml .Values.resolvers.consul.spec | nindent 2 }}
{{ end }}