
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: ambassadortcpmappings.x.getambassador.io
spec:
  group: x.getambassador.io
  names:
    kind: AmbassadorTCPMapping
    listKind: AmbassadorTCPMappingList
    plural: ambassadortcpmappings
    singular: ambassadortcpmapping
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: AmbassadorTCPMapping is the Schema for the tcpmappings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AmbassadorTCPMappingSpec defines the desired state of AmbassadorTCPMapping
          properties:
            address:
              type: string
            ambassador_id:
              description: "AmbassadorID declares which Ambassador instances should pay attention to this resource. If no value is provided, the default is: \n    ambassador_id:    - \"default\""
              items:
                type: string
              type: d6e-union:string,array
            circuit_breakers:
              items:
                properties:
                  max_connections:
                    type: integer
                  max_pending_requests:
                    type: integer
                  max_requests:
                    type: integer
                  max_retries:
                    type: integer
                  priority:
                    enum:
                    - default
                    - high
                    type: string
                type: object
              type: array
            cluster_tag:
              type: string
            enable_ipv4:
              type: boolean
            enable_ipv6:
              type: boolean
            host:
              type: string
            idle_timeout_ms:
              description: 'FIXME(lukeshu): Surely this should be an ''int''?'
              type: string
            port:
              description: Port isn't a pointer because it's required.
              type: integer
            resolver:
              type: string
            service:
              type: string
            tls:
              description: BoolOrString is a type that can hold a Boolean or a string.
              type: d6e-union:string,boolean
            weight:
              type: integer
          required:
          - port
          - service
          type: object
      type: object
  version: v3alpha1
  versions:
  - name: v3alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
