apiVersion: v1
kind: Service
metadata:
  name: {{ template "ambassador.fullname" . }}
  labels:
    app: {{ template "ambassador.name" . }}
    chart: {{ template "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- if .Values.service.enableHttp }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPorts.http }}
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.service.enableHttps }}
    - port: 443
      targetPort: {{ .Values.service.targetPorts.https }}
      protocol: TCP
      name: https
    {{- end }}
  selector:
    app: {{ template "ambassador.name" . }}
    release: {{ .Release.Name }}
