---
apiVersion: v1
kind: Service
metadata:
  name: demo1
  annotations:
    ambassador: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  demo1_mapping
      prefix: /demo/
      service: demo1
spec:
  selector:
    app: demo1
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: dwflynn/demo:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
