---
apiVersion: v1
kind: Service
metadata:
  name: demo2
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  demo_with_header_mapping
      prefix: /demo/
      headers:
        x-demo-mode: canary
      service: demo2
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  demo_with_host_mapping
      prefix: /demo/
      host: demo2.datawire.io
      service: demo2      
spec:
  selector:
    app: demo2
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - name: demo2
        image: dwflynn/demo:2.0.0
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
