# @TEMPLATE@
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: mapping-for-echo
spec:
  prefix: /echo/
  service: echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  type: ClusterIP
  selector:
    service: echo
  ports:
  - name: proxied
    protocol: TCP
    port: 80
    targetPort: 9900
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    service: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: echo
  template:
    metadata:
      labels:
        service: echo
    spec:
      containers:
      - name: echo
        image: jmalloc/echo-server
        ports:
        - containerPort: 8080
      - env:
        - name: APPNAME
          value: echo
        - name: APPPORT
          value: "8080"
        - name: AMBASSADOR_LICENSE_KEY
          value: {{env "AMBASSADOR_LICENSE_KEY"}}
        image: {{env "AES_IMAGE"}}
        command: ["app-sidecar"]
        name: traffic-sidecar
        ports:
        - containerPort: 9900
