---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: invalid-filter
spec:
  JWT:
    jwksURI: not-a-uri
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: invalid-mapping
spec:
  prefix: /invalid/
  service: httpbin.default.svc.cluster.local
  host_rewrite: httpbin.org
  timeout_ms: 5000
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: invalid-policy
spec:
  rules:
    - host: "*"
      path: /invalid/*
      filters:
        - name: invalid-filter
