# @TEMPLATE@

{{ $AmbassadorURL := "https://ambassador.ambassador.svc.cluster.local" }}

# These come directly from https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/3e1ce1e1-094d-4ff5-baed-5ba99e32f809/isMSAApp/
{{ $Azure_Client_ID := "3e1ce1e1-094d-4ff5-baed-5ba99e32f809" }}
{{ $Azure_Tenant_ID := "8538d7d0-9b03-40c9-b72f-378b44ed97e2" }}
# This comes directly from https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Credentials/appId/3e1ce1e1-094d-4ff5-baed-5ba99e32f809/isMSAApp/
{{ $Azure_Client_Secret := "d@HzogM7321tAHXVhI]E]Lt@6.s=TEyb" }}
# Make sure that:
#  - "{{ $AmbassadorURL }}/.ambassador/oauth2/redirection-endpoint" is added as a "Redirect URI" at https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Authentication/appId/3e1ce1e1-094d-4ff5-baed-5ba99e32f809/isMSAApp/
#  - A test user account is set up (and configured in ./tests/cluster/go-test/filter-oauth2/testdata/idp_azure.js)
# The administrator credentials to log in to portal.azure.com are at
#    $(keybase config get -b mountdir)/team/datawireio/secrets/azure.portal.apro-testing.*

---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: azure
spec:
  OAuth2:
    authorizationURL: https://login.microsoftonline.com/{{ $Azure_Tenant_ID }}/v2.0
    protectedOrigins:
    - origin: {{ $AmbassadorURL }}
    - origin: "https://foo.ambassador.svc.cluster.local"
    clientID: {{ $Azure_Client_ID }}
    secret: {{ $Azure_Client_Secret }}
    extraAuthorizationParameters:
      domain_hint: "aprotesting.onmicrosoft.com"
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: filter-oauth2-azure-mapping
spec:
  prefix: /azure/httpbin/
  rewrite: /
  service: httpbin.default.svc.cluster.local
  host_rewrite: httpbin.org
  timeout_ms: 5000
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: filter-oauth2-azure-policy
spec:
  rules:
    - host: "*"
      path: /azure/httpbin/**
      filters:
        - name: azure
          arguments:
            scopes:
              - offline_access # request refresh tokens
---
  apiVersion: v1
  kind: Service
  metadata:
    name: foo
    namespace: ambassador
    labels:
      product: aes
      app.kubernetes.io/component: foo-service
  spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    selector:
      service: ambassador
