---
apiVersion: v1
kind: Service
metadata:
  name: load-http-echo
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: load_testing_base
      prefix: /load-testing/
      service: load-http-echo
spec:
  selector:
    app: load-http-echo
  ports:
  - port: 80
    name: http
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-http-echo
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: load-http-echo
    spec:
      containers:
      - name: qotm
        image: hashicorp/http-echo
        args:
          - "-text='hello world'"
        ports:
        - name: http-api
          containerPort: 5678
