apiVersion: v1
appVersion: 2.1.0
description: A Helm chart for Emissary Ingress
name: emissary-ingress
version: 7.2.0
icon: https://www.getambassador.io/images/logo.png
home: https://www.getambassador.io/
sources:
- https://github.com/datawire/ambassador
- https://github.com/prometheus/statsd_exporter
keywords:
- api gateway
- ambassador
- datawire
- envoy
- emissary
- emissary ingress
maintainers:
- name: flydiverny
  email: markus@maga.se
- name: kflynn
  email: flynn@datawire.io
- name: nbkrause
  email: nkrause@datawire.io
- name: lukeshu
  email: lukeshu@datawire.io
engine: gotpl
