project:
  name: Emissary Ingress
  shortName: Emissary
  url: https://github.com/datawire/ambassador
  description: The Ambassador Edge Stack is a self-service, comprehensive edge stack that is Kubernetes-native and built on [Envoy Proxy](https://www.envoyproxy.io/).
  app: Emissary Ingress
repository:
  url: https://s3.amazonaws.com/datawire-static-files/emissary-charts
  name: emissary-ingress
chart:
  name: emissary-ingress
  version: v0.0.1
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
- "Kubernetes v1.11+"
release:
  name: emissary-ingress
  namespace: ambassador
