---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  namespace: {{ build.profile.namespace }}
spec:
  replicas: {{ build.profile.replicas | default(1) }}
  selector:
    matchLabels:
      app: ambassador
  template:
    metadata:
      labels:
        app: ambassador
    spec:
      serviceAccountName: ambassador
      restartPolicy: Always
      containers:
        - name: ambassador
          image: {{ build.profile.dockerImage }}
          imagePullPolicy: Always
          ports:
            - name: admin
              containerPort: 8877
            - name: envoy
              containerPort: 80
          env:
            - name: SCOUT_DISABLE
              value: "1"
            - name: AMBASSADOR_NAMESPACE
              value: {{ build.profile.namespace }}
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: 8877
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: 8877
            initialDelaySeconds: 10
            periodSeconds: 10
