# general
fullnameOverride: «self.path.k8s»
namespaceOverride: «self.namespace»
deploymentTool: kat

service:
  type: ClusterIP
  portsRaw: "- ←«extra_ports»"
  selector: # affects not just Service.spec.selector but also Pod.metadata.labels
    service: «self.path.k8s»

barePod: true
image:
  fullImageOverride: «images[emissary]»
containerNameOverride: ambassador
restartPolicy: Always
env:
  AMBASSADOR_ID: «self.path.k8s»
  AMBASSADOR_SNAPSHOT_COUNT: "0"
  AMBASSADOR_CONFIG_BASE_DIR: "/tmp/ambassador"
  AMBASSADOR_DISABLE_GO_FILTER: false
envRaw: "- ←«envs»"
security:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    «capabilities_block»♯: null
volumes:
  - name: scratchpad
    emptyDir:
      medium: Memory
      sizeLimit: "45Mi"
volumeMounts:
  - mountPath: /tmp/
    name: scratchpad
resources: null

module: null
agent:
  enabled: false

waitForApiext:
  enabled: false
  deploymentName: «self.path.k8s»-apiext
  deploymentNamespace: «self.namespace»
