---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name:  authentication
      config:
        auth_service: "example-auth:3000"
        path_prefix: "/extauth"
        allowed_headers:
        - "x-extauth-required"
        - "x-authenticated-as"
        - "x-qotm-session"
spec:
  selector:
    service: ambassador
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort