{{- if .Values.module }}
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
  namespace: {{ include "ambassador.namespace" . }}
  labels:
    {{- if ne .Values.deploymentTool "getambassador.io" }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-ratelimit
    {{- end }}
    product: aes
spec:
  {{- if .Values.env }}
  {{- if hasKey .Values.env "AMBASSADOR_ID" }}
  ambassador_id: [ {{ .Values.env.AMBASSADOR_ID | quote }} ]
  {{- end }}
  {{- end }}
  config:
    {{- toYaml .Values.module | nindent 4 }}
{{- end }}
