# GENERATED FILE: edits made by hand will not be preserved.
---
# Source: emissary-ingress/templates/apiext.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador-apiext
  namespace: default
  labels:
    product: aes
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
---
# Source: emissary-ingress/templates/apiext.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-apiext
  labels:
    product: aes
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
rules:
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [list, watch]
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  resourceNames:
  - authservices.getambassador.io
  - consulresolvers.getambassador.io
  - devportals.getambassador.io
  - hosts.getambassador.io
  - kubernetesendpointresolvers.getambassador.io
  - kubernetesserviceresolvers.getambassador.io
  - listeners.getambassador.io
  - logservices.getambassador.io
  - mappings.getambassador.io
  - modules.getambassador.io
  - ratelimitservices.getambassador.io
  - tcpmappings.getambassador.io
  - tlscontexts.getambassador.io
  - tracingservices.getambassador.io
  verbs: [update]
---
# Source: emissary-ingress/templates/apiext.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ambassador-apiext
  labels:
    product: aes
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador-apiext
subjects:
- name: ambassador-apiext
  namespace: default
  kind: ServiceAccount
---
# Source: emissary-ingress/templates/apiext.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ambassador-apiext
  namespace: default
  labels:
    product: aes
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
rules:
- apiGroups: ['']
  resources: [secrets]
  verbs: [create]
- apiGroups: ['']
  resources: [secrets]
  resourceNames: [emissary-ingress-webhook-ca]
  verbs: [get, update]
---
# Source: emissary-ingress/templates/apiext.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ambassador-apiext
  namespace: default
  labels:
    product: aes
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ambassador-apiext
subjects:
- kind: ServiceAccount
  name: ambassador-apiext
  namespace: default
---
# Source: emissary-ingress/templates/apiext.yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador-apiext
  namespace: default
  labels:
    product: aes
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
---
# Source: emissary-ingress/templates/apiext.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-apiext
  namespace: default
  labels:
    product: aes
    app.kubernetes.io/name: ambassador-apiext
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ambassador-apiext
      app.kubernetes.io/part-of: ambassador
      app.kubernetes.io/instance: ambassador
  replicas: 3
  template:
    metadata:
      labels:
        product: aes
        app.kubernetes.io/name: ambassador-apiext
        app.kubernetes.io/part-of: ambassador
        app.kubernetes.io/instance: ambassador
    spec:
      serviceAccountName: ambassador-apiext
      containers:
      - name: ambassador-apiext
        image: docker.io/emissaryingress/emissary:2.0.5
        imagePullPolicy: IfNotPresent
        command: [apiext, ambassador-apiext]
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /probes/live
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 3
---
# Source: emissary-ingress/templates/admin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador-admin
  namespace: default
  labels:
    # Hard-coded label for Prometheus Operator ServiceMonitor
    service: ambassador-admin
    product: aes
  annotations:
    a8r.io/owner: Ambassador Labs
    a8r.io/repository: github.com/datawire/ambassador
    a8r.io/description: The Ambassador Edge Stack admin service for internal use and
      health checks.
    a8r.io/documentation: https://www.getambassador.io/docs/edge-stack/latest/
    a8r.io/chat: http://a8r.io/Slack
    a8r.io/bugs: https://github.com/datawire/ambassador/issues
    a8r.io/support: https://www.getambassador.io/about-us/support/
    a8r.io/dependencies: None
spec:
  type: NodePort
  ports:
  - port: 8877
    targetPort: admin
    protocol: TCP
    name: ambassador-admin
  - port: 8005
    targetPort: 8005
    protocol: TCP
    name: ambassador-snapshot
  selector:
    service: ambassador
---
# Source: emissary-ingress/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: default
  labels:
    app.kubernetes.io/component: ambassador-service
    product: aes
  annotations:
    a8r.io/owner: Ambassador Labs
    a8r.io/repository: github.com/datawire/ambassador
    a8r.io/description: The Ambassador Edge Stack goes beyond traditional API Gateways
      and Ingress Controllers with the advanced edge features needed to support developer
      self-service and full-cycle development.
    a8r.io/documentation: https://www.getambassador.io/docs/edge-stack/latest/
    a8r.io/chat: http://a8r.io/Slack
    a8r.io/bugs: https://github.com/datawire/ambassador/issues
    a8r.io/support: https://www.getambassador.io/about-us/support/
    a8r.io/dependencies: ambassador-redis.default
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  selector:
    service: ambassador
    profile: main
---
# Source: emissary-ingress/templates/rbac.yaml
######################################################################
# Aggregate                                                          #
######################################################################
# This ClusterRole has an empty `rules` and instead sets
# `aggregationRule` in order to aggregate several other ClusterRoles
# together, to avoid the need for multiple ClusterRoleBindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador
  labels:
    product: aes
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.getambassador.io/role-group: ambassador
rules: []
---
# Source: emissary-ingress/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
  namespace: default
  labels:
    product: aes
---
# Source: emissary-ingress/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ambassador
  labels:
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
- name: ambassador
  namespace: default
  kind: ServiceAccount
---
# Source: emissary-ingress/templates/rbac.yaml
######################################################################
# No namespace                                                       #
######################################################################
# These ClusterRoles should be limited to resource types that are
# non-namespaced, and therefore cannot be put in a Role, even if
# Emissary is in single-namespace mode.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-crd
  labels:
    product: aes
    rbac.getambassador.io/role-group: ambassador
rules:
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [get, list, watch, delete]
---
# Source: emissary-ingress/templates/rbac.yaml
######################################################################
# All namespaces                                                     #
######################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-watch
  labels:
    product: aes
    rbac.getambassador.io/role-group: ambassador
rules:
- apiGroups: ['']
  resources:
  - namespaces
  - services
  - secrets
  - endpoints
  verbs: [get, list, watch]

- apiGroups: [getambassador.io]
  resources: ['*']
  verbs: [get, list, watch, update, patch, create, delete]

- apiGroups: [getambassador.io]
  resources: [mappings/status]
  verbs: [update]

- apiGroups: [networking.internal.knative.dev]
  resources: [clusteringresses, ingresses]
  verbs: [get, list, watch]

- apiGroups: [networking.x-k8s.io]
  resources: ['*']
  verbs: [get, list, watch]

- apiGroups: [networking.internal.knative.dev]
  resources: [ingresses/status, clusteringresses/status]
  verbs: [update]

- apiGroups: [extensions, networking.k8s.io]
  resources: [ingresses, ingressclasses]
  verbs: [get, list, watch]

- apiGroups: [extensions, networking.k8s.io]
  resources: [ingresses/status]
  verbs: [update]
---
# Source: emissary-ingress/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  namespace: default
  labels:
    product: aes
spec:
  replicas: 3
  selector:
    matchLabels:
      service: ambassador
  strategy:
    type: RollingUpdate


  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        service: ambassador
        app.kubernetes.io/managed-by: getambassador.io
        profile: main
      annotations:
        consul.hashicorp.com/connect-inject: 'false'
        sidecar.istio.io/inject: 'false'
    spec:
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsUser: 8888
      restartPolicy: Always
      serviceAccountName: ambassador
      volumes:
      - name: ambassador-pod-info
        downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
      containers:
      - name: ambassador
        image: docker.io/emissaryingress/emissary:2.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 8877
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: admin
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: admin
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 3
        volumeMounts:
        - name: ambassador-pod-info
          mountPath: /tmp/ambassador-pod-info
          readOnly: true
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  service: ambassador
              topologyKey: kubernetes.io/hostname
            weight: 100
      imagePullSecrets: []
      dnsPolicy: ClusterFirst
      hostNetwork: false
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador-agent
  namespace: default
  labels:
    product: aes
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ambassador-agent
  labels:
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador-agent
subjects:
- kind: ServiceAccount
  name: ambassador-agent
  namespace: default
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-agent
  labels:
    product: aes
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.getambassador.io/role-group: ambassador-agent
rules: []
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-agent-pods
  labels:
    rbac.getambassador.io/role-group: ambassador-agent
    product: aes
rules:
- apiGroups: ['']
  resources: [pods]
  verbs: [get, list, watch]
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-agent-rollouts
  labels:
    rbac.getambassador.io/role-group: ambassador-agent
    product: aes
rules:
- apiGroups: [argoproj.io]
  resources: [rollouts]
  verbs: [get, list, watch]
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-agent-applications
  labels:
    rbac.getambassador.io/role-group: ambassador-agent
    product: aes
rules:
- apiGroups: [argoproj.io]
  resources: [applications]
  verbs: [get, list, watch]
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-agent-deployments
  labels:
    rbac.getambassador.io/role-group: ambassador-agent
    product: aes
rules:
- apiGroups: [apps, extensions]
  resources: [deployments]
  verbs: [get, list, watch]
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-agent-endpoints
  labels:
    rbac.getambassador.io/role-group: ambassador-agent
    product: aes
rules:
- apiGroups: ['']
  resources: [endpoints]
  verbs: [get, list, watch]
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-agent-configmaps
  labels:
    rbac.getambassador.io/role-group: ambassador-agent
    product: aes
rules:
- apiGroups: ['']
  resources: [configmaps]
  verbs: [get, list, watch]
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ambassador-agent-config
  namespace: default
  labels:
    product: aes
rules:
- apiGroups: ['']
  resources: [configmaps]
  verbs: [get, list, watch]
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ambassador-agent-config
  namespace: default
  labels:
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ambassador-agent-config
subjects:
- kind: ServiceAccount
  name: ambassador-agent
  namespace: default
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-agent
  namespace: default
  labels:
    app.kubernetes.io/name: ambassador-agent
    app.kubernetes.io/instance: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ambassador-agent
      app.kubernetes.io/instance: ambassador
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ambassador-agent
        app.kubernetes.io/instance: ambassador
    spec:
      serviceAccountName: ambassador-agent
      containers:
      - name: agent
        image: docker.io/emissaryingress/emissary:2.0.5
        imagePullPolicy: IfNotPresent
        command: [agent]
        env:
        - name: AGENT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AGENT_CONFIG_RESOURCE_NAME
          value: ambassador-agent-cloud-token
        - name: RPC_CONNECTION_ADDRESS
          value: https://app.getambassador.io/
        - name: AES_SNAPSHOT_URL
          value: http://ambassador-admin.default:8005/snapshot-external
  progressDeadlineSeconds: 600
