deploymentTool: getambassador.io
podAnnotations:
  consul.hashicorp.com/connect-inject: 'false'
  sidecar.istio.io/inject: 'false'
containerNameOverride: ambassador
restartPolicy: Always
terminationGracePeriodSeconds: "0"
service:
  type: LoadBalancer
replicaCount: 3
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            service: ambassador
        topologyKey: kubernetes.io/hostname
      weight: 100

resources:
  limits:
    cpu: 1
    memory: 400Mi
  requests:
    memory: 100Mi
adminService:
  type: NodePort
image:
  repository: "$imageRepo$"
  tag: "$version$"
waitForApiext:
  enabled: true
  createRoles: true

ambassador-agent:
  enabled: true
