---
apiVersion: getambassador.io/v2
kind:  Module
name:  authentication
config:
  auth_service: 127.0.0.1:5050
  path_prefix: /auth/v0/
  allowed_headers:
  - "x-extauth-required"
  - "x-authenticated-as"
  - "x-qotm-session"
