deploymentTool: getambassador.io
redis:
  serviceSelector:
    service: ambassador-redis
replicaCount: 1
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            product: aes
        topologyKey: kubernetes.io/hostname
      weight: 100
env:
  POLL_EVERY_SECS: '60'
  AMBASSADOR_URL: 'https://ambassador.ambassador.svc.cluster.local'
  AMBASSADOR_INTERNAL_URL: 'https://127.0.0.1:8443'
  AMBASSADOR_DRAIN_TIME: '600'
podAnnotations:
  consul.hashicorp.com/connect-inject: 'false'
  sidecar.istio.io/inject: 'false'
containerNameOverride: aes
restartPolicy: Always
terminationGracePeriodSeconds: "0"
service:
  type: LoadBalancer
  selector:
    product: aes
enableTestService: true
deploymentNameOverride: aes
enableAES: true
