fullnameOverride: «self.path.k8s»
namespaceOverride: «self.namespace»
deploymentTool: kat
serviceAccount:
  extra: "«serviceAccountExtra»♯: null"

module: null
agent:
  enabled: false

waitForApiext:
  enabled: false
