name: Trigger CircleCI pipelines for branches

# Because CircleCI gitref filtering is trash, we have CircleCI
# configured to run on
#  - The "default branch" (`master`)
#  - Tags
#  - Pull Requests
# but cannot configure it to run also run on a whitelist of other
# branches; so we have this GitHub action to trigger pipelines on the
# non-`master` branches that we want it to run on.

on:
  push:
    branches:
    - 'release/**'
    - 'shared/**'

jobs:
  "trigger":
    runs-on: ubuntu-latest
    steps:
    - name: Trigger CircleCI pipeline
      env:
        CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
      run: |
        # https://stackoverflow.com/a/22508743
        post() {
          [ "$(set -x; curl -s -i -w '%{http_code}' -o /dev/stderr -X POST "$@")" = 201 ]
        }
        post https://circleci.com/api/v2/project/github/${GITHUB_REPOSITORY}/pipeline \
          -u "$CIRCLECI_TOKEN:" \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          --data "{ \"branch\": \"${GITHUB_REF#refs/heads/}\" }"
